paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod67.json'
  yaml_destination_file: 'data_ymod2.yaml'

source:
  type: object   # file | object

operations:
  - convert_yaml
  - serialize_json
  - stats
